### ISSUE TITLE
Unclear "getting started" instructions

### ISSUE THREAD

**Issue by kjantzer** [JapSeyz/simple-jdf#2]
Using the example in the readme, it appears a laravel project is required?

Can this script be used without?

**Comment by iMusicJJ** [comment]
In all honesty, I haven't tried.. There shouldn't be any issues using it outside of Laravel.

**Comment by kjantzer** [comment]
Hmmm...well it complains about a config file when I try to run outside. I've never used laravel (more of a node.js guy) so I'm not exactly sure how this library is supposed to work with laravel. Oh well, I guess I'll keep doing more research

```
Fatal error: Uncaught ReflectionException: Class config does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:809 Stack trace: #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(809): ReflectionClass->__construct('config') #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\Container\Container->build('config') #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\Container\Container->resolve('config', Array) #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\Container\Container->make('config', Array) #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(275): app('config') #5 /var/www/html/vendor/japseyz/simple-jdf/src/BaseJDF.php(19): config('simple-jdf.auth...', '') #6 /var/www/html/vendor/japseyz/simple-jdf/src/Job.php(15): JapSeyz\SimpleJDF\BaseJDF->__construct() #7 /var/www/html/index.ph in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 811
```

**Comment by iMusicJJ** [comment]
I see. It does use some functions that laravel provide.

Either these functions can be mocked, or a pr/fork is required.

The config function takes a key and returns a value. In laravel this is read from a config file

**Comment by iMusicJJ** [comment]
If you PR this line: https://github.com/JapSeyz/simple-jdf/blob/master/src/BaseJDF.php#L19 with a method_exists

That should fix the config method not existing.
